/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickersRouteImport } from './routes/tickers'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsIndexRouteImport } from './routes/sectors/index'
import { Route as PanicIndexRouteImport } from './routes/panic/index'
import { Route as TickerSymbolRouteImport } from './routes/ticker/$symbol'
import { Route as SectorSectorNameRouteImport } from './routes/sector/$sectorName'
import { Route as PanicAnalyzeRouteImport } from './routes/panic/analyze'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'

const TickersRoute = TickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicIndexRoute = PanicIndexRouteImport.update({
  id: '/panic/',
  path: '/panic/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerSymbolRoute = TickerSymbolRouteImport.update({
  id: '/ticker/$symbol',
  path: '/ticker/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorSectorNameRoute = SectorSectorNameRouteImport.update({
  id: '/sector/$sectorName',
  path: '/sector/$sectorName',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicAnalyzeRoute = PanicAnalyzeRouteImport.update({
  id: '/panic/analyze',
  path: '/panic/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/portfolio': typeof PortfolioRoute
  '/tickers': typeof TickersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/panic/analyze': typeof PanicAnalyzeRoute
  '/sector/$sectorName': typeof SectorSectorNameRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
  '/panic': typeof PanicIndexRoute
  '/sectors': typeof SectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/portfolio': typeof PortfolioRoute
  '/tickers': typeof TickersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/panic/analyze': typeof PanicAnalyzeRoute
  '/sector/$sectorName': typeof SectorSectorNameRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
  '/panic': typeof PanicIndexRoute
  '/sectors': typeof SectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/portfolio': typeof PortfolioRoute
  '/tickers': typeof TickersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/panic/analyze': typeof PanicAnalyzeRoute
  '/sector/$sectorName': typeof SectorSectorNameRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
  '/panic/': typeof PanicIndexRoute
  '/sectors/': typeof SectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/portfolio'
    | '/tickers'
    | '/demo/tanstack-query'
    | '/panic/analyze'
    | '/sector/$sectorName'
    | '/ticker/$symbol'
    | '/panic'
    | '/sectors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/portfolio'
    | '/tickers'
    | '/demo/tanstack-query'
    | '/panic/analyze'
    | '/sector/$sectorName'
    | '/ticker/$symbol'
    | '/panic'
    | '/sectors'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/portfolio'
    | '/tickers'
    | '/demo/tanstack-query'
    | '/panic/analyze'
    | '/sector/$sectorName'
    | '/ticker/$symbol'
    | '/panic/'
    | '/sectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  PortfolioRoute: typeof PortfolioRoute
  TickersRoute: typeof TickersRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PanicAnalyzeRoute: typeof PanicAnalyzeRoute
  SectorSectorNameRoute: typeof SectorSectorNameRoute
  TickerSymbolRoute: typeof TickerSymbolRoute
  PanicIndexRoute: typeof PanicIndexRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickers': {
      id: '/tickers'
      path: '/tickers'
      fullPath: '/tickers'
      preLoaderRoute: typeof TickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panic/': {
      id: '/panic/'
      path: '/panic'
      fullPath: '/panic'
      preLoaderRoute: typeof PanicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticker/$symbol': {
      id: '/ticker/$symbol'
      path: '/ticker/$symbol'
      fullPath: '/ticker/$symbol'
      preLoaderRoute: typeof TickerSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector/$sectorName': {
      id: '/sector/$sectorName'
      path: '/sector/$sectorName'
      fullPath: '/sector/$sectorName'
      preLoaderRoute: typeof SectorSectorNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panic/analyze': {
      id: '/panic/analyze'
      path: '/panic/analyze'
      fullPath: '/panic/analyze'
      preLoaderRoute: typeof PanicAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  PortfolioRoute: PortfolioRoute,
  TickersRoute: TickersRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PanicAnalyzeRoute: PanicAnalyzeRoute,
  SectorSectorNameRoute: SectorSectorNameRoute,
  TickerSymbolRoute: TickerSymbolRoute,
  PanicIndexRoute: PanicIndexRoute,
  SectorsIndexRoute: SectorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
